package main

import (
	"context"
	_ "embed"
	"fmt"
	"slices"
	"strings"

	"buf.build/go/bufplugin/check"
	"buf.build/go/bufplugin/check/checkutil"
	"buf.build/go/bufplugin/descriptor"
	"buf.build/go/bufplugin/info"
	"buf.build/go/bufplugin/option"
	"google.golang.org/protobuf/reflect/protoreflect"
)

var (
	//go:embed README.md
	readmeMarkdown string
)

func main() {
	check.Main(spec)
}

const (
	ruleIDPackageNoLanguageReservedKeywords = "PLUGIN_PACKAGE_NO_LANGUAGE_RESERVED_KEYWORDS"
	ruleIDFieldNoLanguageReservedKeywords   = "PLUGIN_FIELD_NO_LANGUAGE_RESERVED_KEYWORDS"

	// enabledLanguagesOptionKey is the option key to override the default set of enabled
	// languages.
	// By default, all languages are checked.
	enabledLanguagesOptionKey = "enabled_languages"
)

var spec = &check.Spec{
	Rules: []*check.RuleSpec{
		{
			ID:      ruleIDPackageNoLanguageReservedKeywords,
			Default: true,
			Purpose: "Checks that all package names have no components that are language-reserved keywords.",
			Type:    check.RuleTypeLint,
			Handler: checkutil.NewFileRuleHandler(checkPackageNoLanguageReservedKeywords, checkutil.WithoutImports()),
		},
		{
			ID:      ruleIDFieldNoLanguageReservedKeywords,
			Default: true,
			Purpose: "Checks that all field names are not language-reserved keywords.",
			Type:    check.RuleTypeLint,
			Handler: checkutil.NewFieldRuleHandler(checkFieldNoLanguageReservedKeywords, checkutil.WithoutImports()),
		},
	},
	Info: &info.Spec{
		Documentation: readmeMarkdown,
		SPDXLicenseID: "apache-2.0",
		LicenseURL:    "https://github.com/stefanvanburen/buf-check-reserved-keywords/blob/main/LICENSE",
	},
}

func checkPackageNoLanguageReservedKeywords(
	_ context.Context,
	responseWriter check.ResponseWriter,
	request check.Request,
	fileDescriptor descriptor.FileDescriptor,
) error {
	validLanguages, err := getOptions(request)
	if err != nil {
		return fmt.Errorf("parsing options: %w", err)
	}
	packageName := fileDescriptor.FileDescriptorProto().Package
	if packageName == nil {
		return nil
	}
	packageComponents := strings.SplitSeq(*packageName, ".")
	for packageComponent := range packageComponents {
		for language, reservedKeywords := range languageReservedKeywords {
			if !slices.Contains(validLanguages, strings.ToLower(language)) {
				// Skip languages that aren't enabled.
				continue
			}
			if slices.Contains(reservedKeywords, packageComponent) {
				responseWriter.AddAnnotation(
					check.WithMessagef(
						"Package name %q should not use %s reserved keyword %q.",
						*packageName,
						language,
						packageComponent,
					),
					check.WithFileNameAndSourcePath(
						*fileDescriptor.FileDescriptorProto().Name,
						// A well-formed .proto file can only have a single `package` statement;
						// use that location.
						// https://github.com/protocolbuffers/protobuf/blob/6556a4ea26f2273797f559ebad87df42cd540443/src/google/protobuf/descriptor.proto#L109
						[]int32{2},
					),
				)
			}
		}
	}
	return nil
}

func checkFieldNoLanguageReservedKeywords(
	_ context.Context,
	responseWriter check.ResponseWriter,
	request check.Request,
	fieldDescriptor protoreflect.FieldDescriptor,
) error {
	validLanguages, err := getOptions(request)
	if err != nil {
		return fmt.Errorf("parsing options: %w", err)
	}
	for language, reservedKeywords := range languageReservedKeywords {
		if !slices.Contains(validLanguages, strings.ToLower(language)) {
			// Skip languages that aren't enabled.
			continue
		}
		fieldName := string(fieldDescriptor.Name())
		if slices.Contains(reservedKeywords, fieldName) {
			responseWriter.AddAnnotation(
				check.WithMessagef(
					"Field name %q should not use %s reserved keyword %q.",
					fieldName,
					language,
					fieldName,
				),
				check.WithDescriptor(fieldDescriptor),
			)
		}
	}
	return nil
}

func getOptions(request check.Request) (validLanguages []string, err error) {
	// Default to all languages being enabled.
	validLanguages = make([]string, 0, len(languageReservedKeywords))
	for language := range languageReservedKeywords {
		validLanguages = append(validLanguages, strings.ToLower(language))
	}
	enabledLanguagesOptionKey, err := option.GetStringSliceValue(request.Options(), enabledLanguagesOptionKey)
	if err != nil {
		return nil, err
	}
	if len(enabledLanguagesOptionKey) != 0 {
		for _, optionLanguage := range enabledLanguagesOptionKey {
			if !slices.Contains(validLanguages, optionLanguage) {
				return nil, fmt.Errorf("invalid language given %q, expected one of: %q", optionLanguage, strings.Join(validLanguages, ", "))
			}
		}
		// Use the specified languages instead.
		validLanguages = enabledLanguagesOptionKey
	}
	return validLanguages, nil
}

// TODO: Support more languages.
var (
	languageReservedKeywords = map[string][]string{
		// https://en.cppreference.com/w/c/keyword.html
		"C": {
			"auto",
			"break",
			"case",
			"char",
			"const",
			"continue",
			"default",
			"do",
			"double",
			"else",
			"enum",
			"extern",
			"float",
			"for",
			"goto",
			"if",
			"int",
			"long",
			"register",
			"return",
			"short",
			"signed",
			"sizeof",
			"static",
			"struct",
			"switch",
			"typedef",
			"union",
			"unsigned",
			"void",
			"volatile",
			"while",
			"inline",
			"restrict",
			"_Bool",
			"_Complex",
			"_Imaginary",
			"_Alignas",
			"_Alignof",
			"_Atomic",
			"_Generic",
			"_Noreturn",
			"_Static_assert",
			"_Thread_local",
			"alignas",
			"alignof",
			"bool",
			"constexpr",
			"false",
			"nullptr",
			"static_assert",
			"thread_local",
			"true",
			"typeof",
			"typeof_unqual",
			"_BitInt",
			"_Decimal32",
			"_Decimal64",
			"_Decimal128",
			"asm",
			"fortran",
		},
		// https://en.cppreference.com/w/cpp/keyword.html
		"C++": {
			"alignas",
			"alignof",
			"and",
			"and_eq",
			"asm",
			"atomic_cancel",
			"atomic_commit",
			"atomic_noexcept",
			"auto",
			"bitand",
			"bitor",
			"bool",
			"break",
			"case",
			"catch",
			"char",
			"char8_t",
			"char16_t",
			"char32_t",
			"class",
			"compl",
			"concept",
			"const",
			"consteval",
			"constexpr",
			"constinit",
			"const_cast",
			"continue",
			"contract_assert",
			"co_await",
			"co_return",
			"co_yield",
			"decltype",
			"default",
			"delete",
			"do",
			"double",
			"dynamic_cast",
			"else",
			"enum",
			"explicit",
			"export",
			"extern",
			"false",
			"float",
			"for",
			"friend",
			"goto",
			"if",
			"inline",
			"int",
			"long",
			"mutable",
			"namespace",
			"new",
			"noexcept",
			"not",
			"not_eq",
			"nullptr",
			"operator",
			"or",
			"or_eq",
			"private",
			"protected",
			"public",
			"reflexpr",
			"register",
			"reinterpret_cast",
			"requires",
			"return",
			"short",
			"signed",
			"sizeof",
			"static",
			"static_assert",
			"static_cast",
			"struct",
			"switch",
			"synchronized",
			"template",
			"this",
			"thread_local",
			"throw",
			"true",
			"try",
			"typedef",
			"typeid",
			"typename",
			"union",
			"unsigned",
			"using",
			"virtual",
			"void",
			"volatile",
			"wchar_t",
			"while",
			"xor",
			"xor_eq",
		},
		// https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/
		"C#": {
			// Reserved keywords
			"abstract",
			"as",
			"base",
			"bool",
			"break",
			"byte",
			"case",
			"catch",
			"char",
			"checked",
			"class",
			"const",
			"continue",
			"decimal",
			"default",
			"delegate",
			"do",
			"double",
			"else",
			"enum",
			"event",
			"explicit",
			"extern",
			"false",
			"finally",
			"fixed",
			"float",
			"for",
			"foreach",
			"goto",
			"if",
			"implicit",
			"in",
			"int",
			"interface",
			"internal",
			"is",
			"lock",
			"long",
			"namespace",
			"new",
			"null",
			"object",
			"operator",
			"out",
			"override",
			"params",
			"private",
			"protected",
			"public",
			"readonly",
			"ref",
			"return",
			"sbyte",
			"sealed",
			"short",
			"sizeof",
			"stackalloc",
			"static",
			"string",
			"struct",
			"switch",
			"this",
			"throw",
			"true",
			"try",
			"typeof",
			"uint",
			"ulong",
			"unchecked",
			"unsafe",
			"ushort",
			"using",
			"virtual",
			"void",
			"volatile",
			"while",
			// Contextual keywords (can cause issues in generated code)
			"add",
			"alias",
			"ascending",
			"async",
			"await",
			"by",
			"descending",
			"dynamic",
			"equals",
			"from",
			"get",
			"global",
			"group",
			"init",
			"into",
			"join",
			"let",
			"managed",
			"nameof",
			"nint",
			"notnull",
			"nuint",
			"on",
			"orderby",
			"partial",
			"record",
			"remove",
			"required",
			"scoped",
			"select",
			"set",
			"unmanaged",
			"value",
			"var",
			"when",
			"where",
			"with",
			"yield",
		},
		// https://docs.oracle.com/javase/specs/jls/se21/html/jls-3.html#jls-ReservedKeyword
		"Java": {
			// Reserved keywords
			"_",
			"abstract",
			"assert",
			"boolean",
			"break",
			"byte",
			"case",
			"catch",
			"char",
			"class",
			"const",
			"continue",
			"default",
			"do",
			"double",
			"else",
			"enum",
			"extends",
			"final",
			"finally",
			"float",
			"for",
			"goto",
			"if",
			"implements",
			"import",
			"instanceof",
			"int",
			"interface",
			"long",
			"native",
			"new",
			"package",
			"private",
			"protected",
			"public",
			"return",
			"short",
			"static",
			"strictfp",
			"super",
			"switch",
			"synchronized",
			"this",
			"throw",
			"throws",
			"transient",
			"try",
			"void",
			"volatile",
			"while",
			// Contextual keywords (can cause issues in generated code)
			"exports",
			"module",
			"non-sealed",
			"open",
			"opens",
			"permits",
			"provides",
			"record",
			"requires",
			"sealed",
			"to",
			"transitive",
			"uses",
			"var",
			"when",
			"with",
			"yield",
		},
		// https://go.dev/ref/spec#Keywords
		"Go": {
			"break",
			"default",
			"func",
			"interface",
			"select",
			"case",
			"defer",
			"go",
			"map",
			"struct",
			"chan",
			"else",
			"goto",
			"package",
			"switch",
			"const",
			"fallthrough",
			"if",
			"range",
			"type",
			"continue",
			"for",
			"import",
			"return",
			"var",
		},
		"Python": {
			// https://docs.python.org/3/reference/lexical_analysis.html#keywords
			"False",
			"await",
			"else",
			"import",
			"pass",
			"None",
			"break",
			"except",
			"in",
			"raise",
			"True",
			"class",
			"finally",
			"is",
			"return",
			"and",
			"continue",
			"for",
			"lambda",
			"try",
			"as",
			"def",
			"from",
			"nonlocal",
			"while",
			"assert",
			"del",
			"global",
			"not",
			"with",
			"async",
			"elif",
			"if",
			"or",
			"yield",
			// https://docs.python.org/3/reference/lexical_analysis.html#soft-keywords
			"match",
			"case",
			"type",
			"_",
		},
		// https://www.php.net/manual/en/reserved.keywords.php
		"PHP": {
			// Keywords
			"__halt_compiler",
			"abstract",
			"and",
			"array",
			"as",
			"break",
			"callable",
			"case",
			"catch",
			"class",
			"clone",
			"const",
			"continue",
			"declare",
			"default",
			"die",
			"do",
			"echo",
			"else",
			"elseif",
			"empty",
			"enddeclare",
			"endfor",
			"endforeach",
			"endif",
			"endswitch",
			"endwhile",
			"eval",
			"exit",
			"extends",
			"final",
			"finally",
			"fn",
			"for",
			"foreach",
			"function",
			"global",
			"goto",
			"if",
			"implements",
			"include",
			"include_once",
			"instanceof",
			"insteadof",
			"interface",
			"isset",
			"list",
			"match",
			"namespace",
			"new",
			"or",
			"print",
			"private",
			"protected",
			"public",
			"readonly",
			"require",
			"require_once",
			"return",
			"static",
			"switch",
			"throw",
			"trait",
			"try",
			"unset",
			"use",
			"var",
			"while",
			"xor",
			"yield",
			// Compile-time constants (magic constants)
			"__CLASS__",
			"__DIR__",
			"__FILE__",
			"__FUNCTION__",
			"__LINE__",
			"__METHOD__",
			"__NAMESPACE__",
			"__PROPERTY__",
			"__TRAIT__",
		},
		// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords
		"JavaScript": {
			// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words
			"break",
			"case",
			"catch",
			"class",
			"const",
			"continue",
			"debugger",
			"default",
			"delete",
			"do",
			"else",
			"export",
			"extends",
			"false",
			"finally",
			"for",
			"function",
			"if",
			"import",
			"in",
			"instanceof",
			"new",
			"null",
			"return",
			"super",
			"switch",
			"this",
			"throw",
			"true",
			"try",
			"typeof",
			"var",
			"void",
			"while",
			"with",

			"let",
			"static",
			"yield",

			"await",
			// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#future_reserved_words
			"enum",
			"implements",
			"interface",
			"package",
			"private",
			"protected",
			"public",
			"abstract",
			"boolean",
			"byte",
			"char",
			"double",
			"final",
			"float",
			"goto",
			"int",
			"long",
			"native",
			"short",
			"synchronized",
			"throws",
			"transient",
			"volatile",
		},
		// https://dart.dev/language/keywords
		"Dart": {
			"abstract",
			"as",
			"assert",
			"async",
			"await",
			"base",
			"break",
			"case",
			"catch",
			"class",
			"const",
			"continue",
			"covariant",
			"default",
			"deferred",
			"do",
			"dynamic",
			"else",
			"enum",
			"export",
			"extends",
			"extension",
			"external",
			"factory",
			"false",
			"final",
			"finally",
			"for",
			"Function",
			"get",
			"hide",
			"if",
			"implements",
			"import",
			"in",
			"interface",
			"is",
			"late",
			"library",
			"mixin",
			"new",
			"null",
			"of",
			"on",
			"operator",
			"part",
			"required",
			"rethrow",
			"return",
			"sealed",
			"set",
			"show",
			"static",
			"super",
			"switch",
			"sync",
			"this",
			"throw",
			"true",
			"try",
			"type",
			"typedef",
			"var",
			"void",
			"when",
			"with",
			"while",
			"yield",
		},
		// https://doc.rust-lang.org/reference/keywords.html
		"Rust": {
			// Strict keywords
			"_",
			"as",
			"async",
			"await",
			"break",
			"const",
			"continue",
			"crate",
			"dyn",
			"else",
			"enum",
			"extern",
			"false",
			"fn",
			"for",
			"if",
			"impl",
			"in",
			"let",
			"loop",
			"match",
			"mod",
			"move",
			"mut",
			"pub",
			"ref",
			"return",
			"self",
			"Self",
			"static",
			"struct",
			"super",
			"trait",
			"true",
			"type",
			"unsafe",
			"use",
			"where",
			"while",
			// Reserved keywords
			"abstract",
			"become",
			"box",
			"do",
			"final",
			"gen",
			"macro",
			"override",
			"priv",
			"try",
			"typeof",
			"unsized",
			"virtual",
			"yield",
		},
		// https://kotlinlang.org/docs/keyword-reference.html
		"Kotlin": {
			// Hard keywords
			"as",
			"break",
			"class",
			"continue",
			"do",
			"else",
			"false",
			"for",
			"fun",
			"if",
			"in",
			"interface",
			"is",
			"null",
			"object",
			"package",
			"return",
			"super",
			"this",
			"throw",
			"true",
			"try",
			"typealias",
			"typeof",
			"val",
			"var",
			"when",
			"while",
			// Soft keywords
			"by",
			"catch",
			"constructor",
			"delegate",
			"dynamic",
			"field",
			"file",
			"finally",
			"get",
			"import",
			"init",
			"param",
			"property",
			"receiver",
			"set",
			"setparam",
			"value",
			"where",
			// Modifier keywords
			"abstract",
			"actual",
			"annotation",
			"companion",
			"const",
			"crossinline",
			"data",
			"enum",
			"expect",
			"external",
			"final",
			"infix",
			"inline",
			"inner",
			"internal",
			"lateinit",
			"noinline",
			"open",
			"operator",
			"out",
			"override",
			"private",
			"protected",
			"public",
			"reified",
			"sealed",
			"suspend",
			"tailrec",
			"vararg",
			// Special identifiers
			"it",
		},
	}
)
