name: ci
on: push
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - run: just
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          setup_only: true
          token: ${{ secrets.BUF_TOKEN }}
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - run: |
          GOOS=wasip1 GOARCH=wasm go build -o buf-check-reserved-keywords.wasm .
          buf plugin push buf.build/svanburenorg/reserved-keywords \
              --binary=buf-check-reserved-keywords.wasm \
              --source-control-url=https://github.com/${{github.repository}}/commit/${{github.sha}}
