name: Main CI
on:
  push:
    branches:
    - main
  workflow_dispatch: {}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          GOOS=wasip1 GOARCH=wasm go build -o buf-check-reserved-keywords.wasm .
          buf plugin push buf.build/svanburenorg/reserved-keywords \
              --binary=buf-check-reserved-keywords.wasm \
              --create \
              --create-type=check \
              --create-visibility=public
